version: '3.8'

services:
  chat_app:
    build: .
    container_name: chat_ai_app
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-your_secret_key_change_in_production}
      - VERSION=${VERSION:-1.0.0}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./data:/root/script_files/chat/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: chat_ai_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - chat_app
    restart: unless-stopped

